spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/menuDB?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:**/*.xml
  type-aliases-package: com.astb.order.domain

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level %msg%n"

server:
  port: 9777